# __ GeneralRecommender ________________________________________________________
is_multimodal_model: false
end2end: false

# __ Dataset / KG triples _____________________________________________________
model_enriched_triples_format: true
dataset_support_triples: true

# __ Core hyperparameters ____________________________
embedding_size: 64          
relation_dim: 64           

conv_dim_list: '[64, 32, 16]'

aggregation_type: 'bi-interaction'
aggregator_bias: True       

mess_dropout: [0.1, 0.1, 0.1]

# __ Loss weights ______________________________________________________________
reg_weight: 0.001         
kg_loss_weight: 1.0         

# __ Optimiser _________________________________________________________________
learning_rate: [0.0001]     
kg_batch_size: 2048         
clip_grad_norm: 1.0

seed: [2019]                
epochs: 1000                
stopping_step: 5
eval_step: 10          
train_batch_size: 1024      
eval_batch_size: 10000      

# __ Hyper-parameter search axes _______________________________________________
hyper_parameters: ["learning_rate"]
