# ──GeneralRecommender ──────────────────────────────
is_multimodal_model: true
end2end: False
vision_feature_file: image_feat.npy   
text_feature_file:   text_feat.npy    


# ── Hyperparameters ─────────────────────────────────────────────────────────────
leaky_relu_slope: 0.01
reg_weight: [0.005, 0.0001]
learning_rate: [0.00005, 0.0005]
modality_dropout_ratio: [0.2, 0.1]
n_layers: [1,2,3]
dropout_ratio: [0.25, 0.5]
hyper_parameters: ["reg_weight", "learning_rate", "modality_dropout_ratio", "n_layers", "dropout_ratio"]

# ── Learning ─────────────────────────────────────────────────────────────
clip_grad_norm: 1.0
 

# ── Representation format ─────────────────────────────────────────────────────────────
model_enriched_triples_format: True # We have triples covering the user-item, item-item and the item-attributes relations